version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install AWS CLI"
      - yum install unzip -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install

  pre_build:
    commands:
      - echo "N/A"
  build:
    commands:
      - echo "Build Step Sync Files to Bucket S3"
      - unzip web.zip 
      - aws s3 sync web/. s3://devtf-stratusgrid-website
  post_build:
    commands:
      - echo "Delete temp files"
      - rm *.zip
      - rm -rf web
      - echo "Invalidation Cloudfront" 
      - aws cloudfront create-invalidation --distribution-id E2DMPE5KNRQ7DL --paths '/*'